<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('theloai')->insert([
            ['id'=>1,'ten'=>'Vui chơi', 'tenkhongdau'=>'Vui-choi'],
            ['id'=>2,'ten'=>'Học tập', 'tenkhongdau'=>'Hoc-tap'],
            ['id'=>3,'ten'=>'Nghỉ ngơi', 'tenkhongdau'=>'Nghi-ngoi'],
            ['id'=>4,'ten'=>'Môi trường', 'tenkhongdau'=>'Moi-truong'],
            ['id'=>5,'ten'=>'Hoạt động', 'tenkhongdau'=>'Hoat-dong'],
            ['id'=>6,'ten'=>'Thông báo', 'tenkhongdau'=>'Thong-bao'],
            ['id'=>7,'ten'=>'Học phí', 'tenkhongdau'=>'Hoc-phi'],
        ]);
        DB::table('loaitin')->insert([
            ['id'=>1,'idtheloai'=>'1', 'ten'=>'Giờ giải lao sáng', 'tenkhongdau'=>'Gio-giai-lao-sang', 'id_theloai'=>'1'],
            ['id'=>2,'idtheloai'=>'4', 'ten'=>'Khu tập hợp', 'tenkhongdau'=>'khu-tap-hop', 'id_theloai'=>'4'],
            ['id'=>3,'idtheloai'=>'2', 'ten'=>'Học buổi sáng', 'tenkhongdau'=>'hoc-buoi-sang', 'id_theloai'=>'2'],
            ['id'=>4,'idtheloai'=>'6', 'ten'=>'Thông báo nghỉ dịch', 'tenkhongdau'=>'thong-bao-nghi-dich', 'id_theloai'=>'6'],
            ['id'=>5,'idtheloai'=>'5', 'ten'=>'Hoạt động ngoại khóa', 'tenkhongdau'=>'hoat-dong-ngoai-khoa', 'id_theloai'=>'5'],
            ['id'=>6,'idtheloai'=>'1', 'ten'=>'Giờ giải lao chiều', 'tenkhongdau'=>'gio-giai-lao-chieu', 'id_theloai'=>'1'],
            ['id'=>7,'idtheloai'=>'7', 'ten'=>'Tăng phí lắp đặt', 'tenkhongdau'=>'tang-phi-lap-dat', 'id_theloai'=>'7'],
            ['id'=>8,'idtheloai'=>'3', 'ten'=>'Ngủ trưa', 'tenkhongdau'=>'ngu-trua', 'id_theloai'=>'3'],
            ['id'=>9,'idtheloai'=>'2', 'ten'=>'Học buổi chiều', 'tenkhongdau'=>'hoc-buoi-chieu', 'id_theloai'=>'2'],
            ['id'=>10,'idtheloai'=>'6', 'ten'=>'Thông báo họp phụ huynh', 'tenkhongdau'=>'thong-bao-hop-phu-huynh', 'id_theloai'=>'6'],
            ['id'=>11,'idtheloai'=>'4', 'ten'=>'Sân chơi', 'tenkhongdau'=>'san-choi', 'id_theloai'=>'4'],
            ['id'=>12,'idtheloai'=>'5', 'ten'=>'Hoạt động tham quan', 'tenkhongdau'=>'hoat-dong-tham-quan', 'id_theloai'=>'5'],
            ['id'=>13,'idtheloai'=>'3', 'ten'=>'Ăn trưa', 'tenkhongdau'=>'an-trua', 'id_theloai'=>'3'],
            ['id'=>14,'idtheloai'=>'7', 'ten'=>'Tăng phí sinh hoạt', 'tenkhongdau'=>'tang-phi-sinh-hoat', 'id_theloai'=>'7'],
            ['id'=>15,'idtheloai'=>'5', 'ten'=>'Hoạt động ngoài giờ', 'tenkhongdau'=>'hoat-dong-ngoai-gio', 'id_theloai'=>'5'],
            ['id'=>16,'idtheloai'=>'1', 'ten'=>'Giờ giải lao thêm', 'tenkhongdau'=>'gio-giai-lao-them', 'id_theloai'=>'1'],
            ['id'=>18,'idtheloai'=>'6', 'ten'=>'Thông báo nghỉ học', 'tenkhongdau'=>'thong-bao-nghi-hoc', 'id_theloai'=>'6'],
            ['id'=>19,'idtheloai'=>'2', 'ten'=>'Học ngoại khóa', 'tenkhongdau'=>'hoc-ngoai-khoa', 'id_theloai'=>'2'],
            ['id'=>20,'idtheloai'=>'4', 'ten'=>'Phòng học', 'tenkhongdau'=>'phong-hoc', 'id_theloai'=>'4'],
        ]);
        DB::table('tintuc')->insert([
            ['id'=>1,'tieude'=>'Phòng học hàng ngày', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Phòng học đầy đủ các dụng cụ cần thiết với các bé',
                'noidung'=>'<h1>Tuyên truyền phòng, chống dịch Covid – 19 cho học sinh, sinh viên</h1><br/><p>Sáng ngày 11 tháng 03 năm 2020 Thực hiện phòng chống dịch Covid – 19, Cán </p>',
                'hinh'=>'1.jpg', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'20', 'loaitin_id'=>'20'],
            ['id'=>2,'tieude'=>'Buổi ngoại khóa', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Buổi học ngoại khóa hàng tuần',
                'noidung'=>'<h1>HOẠT ĐỘNG VUI CHƠI BỔ ÍCH MỖI GIỜ GIẢI LAO LỚP 2/6</h1><br/><p>Thông báo khẩn Sở GD & ĐT muốn xin ý kiến của phụ huynh về việc đi học lại của học sinh. </p>',
                'hinh'=>'2.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'19', 'loaitin_id'=>'19'],
            ['id'=>3,'tieude'=>'Thông báo nghỉ', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'Thông báo nghỉ khẩn',
                'noidung'=>'<h1>THÔNG BÁO KHẨN V/v cho học sinh được nghỉ học từ 8/2 - 16/2/2020</h1><br/><p>Thực hiện chỉ đạo theo Cv số 195/SGD&ĐT-VP của Giám đốc Sở Giáo dục & Đào tạo Bến </p>',
                'hinh'=>'3.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'18', 'loaitin_id'=>'18'],
            ['id'=>5,'tieude'=>'Giải lao', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Giải lao tăng tính tập thể',
                'noidung'=>'<h1>Mạng xã hội đang thay đổi mối quan hệ thầy trò?</h1><br/><p>Hình ảnh một nam sinh tát cô giáo trong đoạn clip lan truyền trên mạng không ngừng gây xôn xao, </p>',
                'hinh'=>'4.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'16', 'loaitin_id'=>'16'],
            ['id'=>6,'tieude'=>'Hoạt động tưới cây', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'Hoạt động tăng tính linh hoạt cho bé',
                'noidung'=>'<h1>Tăng cường hoạt động trải nghiệm cho học sinh</h1><br/><p>Trước yêu cầu đổi mới căn bản, toàn diện giáo dục và đào tạo, năm học vừa qua, Sở Giáo dục và Đào tạo </p>',
                'hinh'=>'6.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'15', 'loaitin_id'=>'15'],
            ['id'=>7,'tieude'=>'Tăng học phí', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'Tăng học phí sinh hoạt',
                'noidung'=>'<h1>Hà Nội tăng học phí một số cấp học: Để tái đầu tư, nâng chất lượng giáo dục</h1><br/><p>(HNM) - Theo nghị quyết vừa được HĐND thành phố thông qua, từ năm học 2</p>',
                'hinh'=>'7.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'14', 'loaitin_id'=>'14'],
            ['id'=>8,'tieude'=>'Giờ ăn trưa', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'Các bé giời ăn trưa',
                'noidung'=>'<h1>Bữa trưa vui vẻ của các bé khi ở trường</h1><br/><p>Tạo không khí vui vẻ trong bữa ăn cho trẻ, thể hiện qua nét mặt, cử chỉ, lời nói...của người chăm sóc. Điề</p>',
                'hinh'=>'8.jpg','noibat'=>'0', 'soluotxem'=>'0',
                'idloaitin'=>'13', 'loaitin_id'=>'13'],
            ['id'=>9,'tieude'=>'Tham quan hằng năm', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'Thăm quan tăng kiến thức cho bé',
                'noidung'=>'<h1>Chùa Bái Đính “hút” khách về tham quan, chiêm bái</h1><br/><p>Thành thông lệ hàng năm, ngày mùng 6 Tết Âm lịch là ngày khai hội chùa Bái Đính, khởi đầu cho lễ hội m</p>',
                'hinh'=>'9.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'12', 'loaitin_id'=>'12'],
            ['id'=>10,'tieude'=>'Sân chơi của trường', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'Khu vui chơi của các bé',
                'noidung'=>'<h1>SÂN CHƠI TRƯỜNG MẦM NON HOA HỒNG</h1><br/><p>Trường mầm non là nơi các bé được học tập, vui chơi giải trí, các bé cần được thỏa sức sáng tạo trong các trò chơi và </p>',
                'hinh'=>'10.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'11', 'loaitin_id'=>'11'],
            ['id'=>11,'tieude'=>'Buổi học phụ huynh', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Thông báo họp phụ huynh hằng năm',
                'noidung'=>'<h1>Kịch bản họp phụ huynh đầu năm trường Mầm non (3 mẫu)</h1><br/><p>Kịch bản họp phụ huynh đầu năm trường Mầm non gồm 3 mẫu, giúp thầy cô dễ dàng xây dựng chương trìn</p>',
                'hinh'=>'11.jpg', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'10', 'loaitin_id'=>'10'],
            ['id'=>12,'tieude'=>'Giờ học chiều', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Các bé trong thời gian học buổi chiều',
                'noidung'=>'<h1>Giờ học buổi chiều của lớp nhỡ A</h1><br/><p>Những con ông chăm chỉ...  Yêu  các con nhiều </p><br/><p>Cùng nhau thi tài...  Những Đôi bàn tay khéo léo và dễ thương </p>',
                'hinh'=>'12.jpg','noibat'=>'0', 'soluotxem'=>'0',
                'idloaitin'=>'9', 'loaitin_id'=>'9'],
            ['id'=>13,'tieude'=>'Giờ ngủ trưa', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'Các bé trong giờ ngủ trưa',
                'noidung'=>'<h1>GIỜ NGỦ TRƯA CỦA CÁC BÉ TRƯỜNG MẦM NON NGÔ QUYỀN</h1><br/><p>Trẻ em trong lứa tuổi mầm non cần được đến trường để đảm bảo phát triển tốt nhất về trí tuệ, tâm lý, thể thất, tình cảm. Nhiệm vụ </p>',
                'hinh'=>'13.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'8', 'loaitin_id'=>' 8'],
            ['id'=>14,'tieude'=>'Thông tin tăng phí', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'Để tăng các dịch vụ cho các bé',
                'noidung'=>'<h1>Hà Nội tăng học phí từ giáo dục mầm non đến THPT năm học 2018-2019</h1><br/><p>Chiều 5/7, HĐND TP Hà Nội đã thông qua Nghị quyết quy định mức thu học phí đối với giáo dục mầm non, giáo dục phổ </p>',
                'hinh'=>'14.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'7', 'loaitin_id'=>'7'],
            ['id'=>15,'tieude'=>'Hoạt động vui chơi buổi chiều', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Các bé trong thời gian vui chơi buổi chiều',
                'noidung'=>'<h1>Duy trì hoạt động của trẻ tại các góc thiên nhiên sau "Hội thi cây 2019" của trường mầm non Chim Non</h1><br/><p>Hội thi cây Xuân Kỷ Hợi 2019 của trường mầm non Chim Non đã diễn ra gần 2 tháng</p>',
                'hinh'=>'15.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'6', 'loaitin_id'=>'6'],
            ['id'=>16,'tieude'=>'Hoạt động thêm cho bé', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'Tạo hoạt động trồng cây cho các bé',
                'noidung'=>'<h1>Hoạt động buổi chiều của các bé lớp mẫu giáo bé C2</h1><br/><p>Khi bé ở trường học, bé được hoạt động trong thời gian biểu hợp lý, kết hợp khoa học các hoạt động học tập, vui chơi, nghỉ ngơi, ă</p>',
                'hinh'=>'16.jpg','noibat'=>'0', 'soluotxem'=>'0',
                'idloaitin'=>'5', 'loaitin_id'=>'5'],
            ['id'=>17,'tieude'=>'Nghỉ dịch', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'Báo khẩn nghỉ do dịch',
                'noidung'=>'<h1>Hà Nội xem xét cho học sinh tiếp tục nghỉ học để phòng chống dịch COVID-19 từ ngày 17/2<h1/><br/>
<p>Sở Giáo dục và Đào tạo Hà Nội vừa có tờ trình đề xuất cho toàn bộ học sinh ở Hà Nội tạm dừn.</p>',
                'hinh'=>'17.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'4'],
            ['id'=>18,'tieude'=>'Giờ học sáng', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'Thời gian học sáng của các bé',
                'noidung'=>'<h1>Giờ học tạo hình: Bàn tay sáng tạo</h1><br/>
<p>Ngoài nhu cầu trang bị kiến thức trên lớp, phục vụ cho phát triển khả năng tư duy, thì các hoạt động ngoại khóa là cơ sở quan trọng để các em học sinh phát huy khả năng, nă,</p>',
                'hinh'=>'18.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'3', 'loaitin_id'=>'3'],
            ['id'=>19,'tieude'=>'Giờ vui chơi sáng', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'Thời gian hoạt động vui chơi sáng của các bé',
                'noidung'=>'<h1>Giờ ra chơi trải nghiệm, sáng tạo</h1><br/>
<p>Ngoài nhu cầu trang bị kiến thức trên lớp, phục vụ cho phát triển khả năng tư duy, thì các hoạt động ngoại khóa là cơ sở quan trọng để các em học sinh phát huy khả năng, nă,</p>',
                'hinh'=>'19.jpg','noibat'=>'0', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'2'],
            ['id'=>20,'tieude'=>'Nơi tập chung các bé', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'Địa điểm tập chung các bé hàng ngày',
                'noidung'=>'<h1>Bài 2: Hiệu quả nhờ sự quyết liệt</h1><br/><h4>TTTĐ -  địa bàn thành phố Hà Nội đã quyết liệt  lại sân chơi cho người dân và trẻ em. Những không gian cũ kỹ, lộn xộn giữa các khối nhà tập thể bất ngờ thay đổi diện mạo, biến thành khu vui a.</h4><br/>',
                'hinh'=>'20.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'5', 'loaitin_id'=>'1'],
            ['id'=>21,'tieude'=>'Phòng học hàng ngày', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Phòng học đầy đủ các dụng cụ cần thiết với các bé',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'11.jpg', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'12', 'loaitin_id'=>'20'],
            ['id'=>22,'tieude'=>'Buổi ngoại khóa', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Buổi học ngoại khóa hàng tuần',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'12.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'11', 'loaitin_id'=>'19'],
            ['id'=>23,'tieude'=>'Thông báo nghỉ', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'Thông báo nghỉ khẩn',
                'noidung'=>'Đi học5',
                'hinh'=>'13.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'17', 'loaitin_id'=>'18'],
            ['id'=>25,'tieude'=>'Giải lao', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Giải lao tăng tính tập thể',
                'noidung'=>'Đã thành công tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'11.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'2', 'loaitin_id'=>'16'],
            ['id'=>26,'tieude'=>'Hoạt động tưới cây', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'Hoạt động tăng tính linh hoạt cho bé',
                'noidung'=>'Đi học3',
                'hinh'=>'20.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'7', 'loaitin_id'=>'15'],
            ['id'=>27,'tieude'=>'Tăng học phí', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'Tăng học phí sinh hoạt',
                'noidung'=>'Đi nghiệp phát triển ngông',
                'hinh'=>'17.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'1', 'loaitin_id'=>'14'],
            ['id'=>28,'tieude'=>'Giờ ăn trưa', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'Các bé giời ăn trưa',
                'noidung'=>'Đi học',
                'hinh'=>'12.jpg','noibat'=>'0', 'soluotxem'=>'0',
                'idloaitin'=>'9', 'loaitin_id'=>'13'],
            ['id'=>29,'tieude'=>'Tham quan hằng năm', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'Thăm quan tăng kiến thức cho bé',
                'noidung'=>'nghiệp phát triển',
                'hinh'=>'13.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'13', 'loaitin_id'=>'12'],
            ['id'=>30,'tieude'=>'Sân chơi của trường', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'Khu vui chơi của các bé',
                'noidung'=>'nghiệp phát triển ngông',
                'hinh'=>'16.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'12', 'loaitin_id'=>'11'],
            ['id'=>31,'tieude'=>'Buổi học phụ huynh', 'tieudekhongdau'=>'h-m-nay-an-cai-g-',
                'tomtat'=>'Thông báo họp phụ huynh hằng năm',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'6.jpg', 'noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'13', 'loaitin_id'=>'10'],
            ['id'=>32,'tieude'=>'Giờ học chiều', 'tieudekhongdau'=>'h-m-nay-an-g-lo-',
                'tomtat'=>'Các bé trong thời gian học buổi chiều',
                'noidung'=>'Đi học Đi học',
                'hinh'=>'10.jpg','noibat'=>'0', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'9'],
            ['id'=>33,'tieude'=>'Giờ ngủ trưa', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'Các bé trong giờ ngủ trưa',
                'noidung'=>'Đi học5',
                'hinh'=>'7.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'7', 'loaitin_id'=>' 8'],
            ['id'=>34,'tieude'=>'Thông tin tăng phí', 'tieudekhongdau'=>'h-m-nay-an-g-ta-',
                'tomtat'=>'Để tăng các dịch vụ cho các bé',
                'noidung'=>'tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'3.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'10', 'loaitin_id'=>'7'],
            ['id'=>35,'tieude'=>'Hoạt động vui chơi buổi chiều', 'tieudekhongdau'=>'hien-th-10',
                'tomtat'=>'Các bé trong thời gian vui chơi buổi chiều',
                'noidung'=>'Đã thành công tạo giống mới cho nông nghiệp phát triển',
                'hinh'=>'8.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'8', 'loaitin_id'=>'6'],
            ['id'=>36,'tieude'=>'Hoạt động thêm cho bé', 'tieudekhongdau'=>'hien-th-3',
                'tomtat'=>'Tạo hoạt động trồng cây cho các bé',
                'noidung'=>'Đi học3',
                'hinh'=>'4.jpg','noibat'=>'0', 'soluotxem'=>'0',
                'idloaitin'=>'13', 'loaitin_id'=>'5'],
            ['id'=>37,'tieude'=>'Nghỉ dịch', 'tieudekhongdau'=>'nghiep-phat-trien-ng-ng',
                'tomtat'=>'Báo khẩn nghỉ do dịch',
                'noidung'=>'Đi nghiệp phát triển ngông',
                'hinh'=>'2.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'14', 'loaitin_id'=>'4'],
            ['id'=>38,'tieude'=>'Giờ học sáng', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'Thời gian học sáng của các bé',
                'noidung'=>'Đi học',
                'hinh'=>'1.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'12', 'loaitin_id'=>'3'],
            ['id'=>39,'tieude'=>'Giờ vui chơi sáng', 'tieudekhongdau'=>'phat-trien',
                'tomtat'=>'Thời gian hoạt động vui chơi sáng của các bé',
                'noidung'=>'nghiệp phát triển',
                'hinh'=>'9.jpg','noibat'=>'0', 'soluotxem'=>'0',
                'idloaitin'=>'5', 'loaitin_id'=>'2'],
            ['id'=>40,'tieude'=>'Nơi tập chung các bé', 'tieudekhongdau'=>'trien-ng-ng',
                'tomtat'=>'Địa điểm tập chung các bé hàng ngày',
                'noidung'=>'nghiệp phát triển ngông',
                'hinh'=>'5.jpg','noibat'=>'1', 'soluotxem'=>'0',
                'idloaitin'=>'4', 'loaitin_id'=>'1'],
        ]);
        DB::table('comment')->insert([
            ['id'=>1,'iduser'=>'1', 'idtintuc'=>'1', 'noidung'=>'Hay', 'luotthich'=>'1', 'tintuc_id'=>'1'],
        ]);
        DB::table('commentdetail')->insert([
            ['id'=>1,'iduser'=>'1', 'idcomment'=>'1', 'noidung'=>'Hay', 'luotthich'=>'1', 'comment_id'=>'1'],
        ]);
        DB::table('slide')->insert([
            ['id'=>1,'ten'=>'slide 1', 'hinh'=>'sl.png', 'noidung'=>'Hay1', 'link'=>'11'],
            ['id'=>2,'ten'=>'slide 2', 'hinh'=>'sl2.jpg', 'noidung'=>'Hay2', 'link'=>'12'],
            ['id'=>3,'ten'=>'slide 3', 'hinh'=>'sl3.jpg', 'noidung'=>'Hay3', 'link'=>'13'],
        ]);
        DB::table('users')->insert([
            ['id'=>1,'username'=>'Nguyễn Quyết', 'name'=>'Chiến', 'avatar'=>'111.jpg', 'email'=>'orangen2000k@gmail.com',
                'password'=>bcrypt('chien@123'), 'phoneNumber'=>'0963328520', 'birthYear'=>'11/10/2000',
                'active'=>'1', 'streetInformation'=>'Thôn 7, Trung Châu, Đan Phượng', 'province'=>'Hà Nội',
                'summary'=>'Thích đọc truyện, xem phim, ăn, ngủ :3', 'level'=>'1', 'comment_id'=>'1'],
            ['id'=>2,'username'=>'Trần Việt', 'name'=>'Chinh', 'avatar'=>'1111.jpg', 'email'=>'orangen2000@gmail.com',
                'password'=>bcrypt('chinh@123'), 'phoneNumber'=>'0963328520', 'birthYear'=>'11/10/2000',
                'active'=>'1', 'streetInformation'=>'Thôn 10, Trung Châu, Đan Phượng', 'province'=>'Hà Nội',
                'summary'=>'Thích đọc truyện, xem phim, ăn, ngủ :3', 'level'=>'0', 'comment_id'=>'1'],
        ]);
        DB::table('dondangky')->insert([
            ['id'=>1,'hodem'=>'Nguyễn Quyết', 'ten'=>'Chiến', 'anh'=>'111.jpg', 'email'=>'chien@gmail.com',
                'sodienthoai'=>'0963328520', 'ngaysinh'=>'11/10/2000', 'gioitinh'=>'1',
                'trangthai'=>'0','diachi'=>'Thôn 7, Trung Châu, Đan Phượng', 'thanhpho'=>'Hà Nội',
                'gioithieu'=>'Thích đọc truyện, xem phim, ăn, ngủ :3', 'iduser'=>'1'],
            ['id'=>2,'hodem'=>'Nguyễn Quyết', 'ten'=>'Chiến', 'anh'=>'111.jpg', 'email'=>'chien@gmail.com',
                'sodienthoai'=>'0963328520', 'ngaysinh'=>'11/10/2000', 'gioitinh'=>'1',
                'trangthai'=>'0','diachi'=>'Thôn 7, Trung Châu, Đan Phượng', 'thanhpho'=>'Hà Nội',
                'gioithieu'=>'Thích đọc truyện, xem phim, ăn, ngủ :3', 'iduser'=>'1'],
            ['id'=>3,'hodem'=>'Nguyễn Quyết', 'ten'=>'Chiến', 'anh'=>'111.jpg', 'email'=>'chien@gmail.com',
                'sodienthoai'=>'0963328520', 'ngaysinh'=>'11/10/2000', 'gioitinh'=>'1',
                'trangthai'=>'0','diachi'=>'Thôn 7, Trung Châu, Đan Phượng', 'thanhpho'=>'Hà Nội',
                'gioithieu'=>'Thích đọc truyện, xem phim, ăn, ngủ :3', 'iduser'=>'1'],
            ['id'=>4,'hodem'=>'Nguyễn Quyết', 'ten'=>'Chiến', 'anh'=>'111.jpg', 'email'=>'chien@gmail.com',
                'sodienthoai'=>'0963328520', 'ngaysinh'=>'11/10/2000', 'gioitinh'=>'1',
                'trangthai'=>'0','diachi'=>'Thôn 7, Trung Châu, Đan Phượng', 'thanhpho'=>'Hà Nội',
                'gioithieu'=>'Thích đọc truyện, xem phim, ăn, ngủ :3', 'iduser'=>'1'],
        ]);
    }
}
